sonar.projectKey=cristianogomesalbino_bolao-frontend
sonar.organization=cristianogomesalbino

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

# Exclusões de análise
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**
sonar.coverage.exclusions=**/types/**,**/constants/**,**/*.d.ts
